/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlScannerRouteImport } from './routes/url-scanner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PhoneScannerRouteImport } from './routes/phone-scanner'
import { Route as NewsRouteImport } from './routes/news'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UrlScannerRoute = UrlScannerRouteImport.update({
  id: '/url-scanner',
  path: '/url-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneScannerRoute = PhoneScannerRouteImport.update({
  id: '/phone-scanner',
  path: '/phone-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyzer': typeof AnalyzerRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/news': typeof NewsRoute
  '/phone-scanner': typeof PhoneScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/url-scanner': typeof UrlScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyzer': typeof AnalyzerRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/news': typeof NewsRoute
  '/phone-scanner': typeof PhoneScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/url-scanner': typeof UrlScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyzer': typeof AnalyzerRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/news': typeof NewsRoute
  '/phone-scanner': typeof PhoneScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/url-scanner': typeof UrlScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyzer'
    | '/auth'
    | '/dashboard'
    | '/news'
    | '/phone-scanner'
    | '/sitemap.xml'
    | '/url-scanner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyzer'
    | '/auth'
    | '/dashboard'
    | '/news'
    | '/phone-scanner'
    | '/sitemap.xml'
    | '/url-scanner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyzer'
    | '/auth'
    | '/dashboard'
    | '/news'
    | '/phone-scanner'
    | '/sitemap.xml'
    | '/url-scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzerRoute: typeof AnalyzerRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  NewsRoute: typeof NewsRoute
  PhoneScannerRoute: typeof PhoneScannerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UrlScannerRoute: typeof UrlScannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url-scanner': {
      id: '/url-scanner'
      path: '/url-scanner'
      fullPath: '/url-scanner'
      preLoaderRoute: typeof UrlScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-scanner': {
      id: '/phone-scanner'
      path: '/phone-scanner'
      fullPath: '/phone-scanner'
      preLoaderRoute: typeof PhoneScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzerRoute: AnalyzerRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  NewsRoute: NewsRoute,
  PhoneScannerRoute: PhoneScannerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UrlScannerRoute: UrlScannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
